In [4]:
import numpy as np
#FOR INTEGERS
a=np.random.default_rng(seed=1) #seed is used for always getting the same array as an output.
print(a.integers(1, 51, 5))     #start value, stop value, number of values 
print("")

#for getting it as a 2d array.
print(a.integers(1, 51, size=(2,2)))
print("")

#FOR FLOATING POINT NUMBERS
np.random.seed(seed=1)
print(np.random.uniform(0, 10, size=(2,2))) # In uniform() each value has uniform or equal chance of its occurance

[24 26 38 48  2]

[[ 8 42]
 [48 13]]

[[4.17022005e+00 7.20324493e+00]
 [1.14374817e-03 3.02332573e+00]]


In [17]:
#SHUFFLING AN ARRAY
s=np.random.default_rng()
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
print(arr)
print("")

#Using shuffle() to shuffle the rows of the array
print("after shuffling") 
s.shuffle(arr)  #It will shuffle the original array
print(arr)





[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

after shuffling
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [ 6  7  8  9 10]]


In [18]:
s=np.random.default_rng()
arr=(["apple🍏","banana","orange🍊","coconut🥥","mango🥭"]) # press(win + ;) for emojis
ch=s.choice(arr) #prints a random element
print(ch)

ch=s.choice(arr,size=(4,4)) #prints specified num of random elements
print(ch)

apple🍏
[['mango🥭' 'orange🍊' 'apple🍏' 'apple🍏']
 ['coconut🥥' 'banana' 'apple🍏' 'orange🍊']
 ['apple🍏' 'banana' 'mango🥭' 'orange🍊']
 ['banana' 'banana' 'apple🍏' 'coconut🥥']]
